        ; This file is programmatically generated by worlded utility

                include bg/world.s

        ; Check for bitarea size exceeded

                if LVLDATAACTTOTALSIZE+LVLOBJTOTALSIZE > 255
                    err
                endif
